# Generated by Django 5.2 on 2025-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'قيد التنفيذ'), (2, 'مكتمل'), (3, 'معلق'), (4, 'ملغي')], default=1),
        ),
    ]
